using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BehaviourTree.SourceGenerators
{
    /// <summary>
    /// Source Generator that creates compile-time metadata for all behavior tree nodes,
    /// eliminating reflection overhead from GetType().Name and GetType().FullName calls.
    /// </summary>
    [Generator]
    public class BehaviourMetadataGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new BehaviourSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not BehaviourSyntaxReceiver receiver)
                return;

            var compilation = context.Compilation;
            var behaviourTypes = new List<INamedTypeSymbol>();

            // Find all types that implement IBehaviour or BaseBehaviour
            foreach (var candidateClass in receiver.CandidateClasses)
            {
                var model = compilation.GetSemanticModel(candidateClass.SyntaxTree);
                var typeSymbol = model.GetDeclaredSymbol(candidateClass) as INamedTypeSymbol;

                if (typeSymbol == null)
                    continue;

                // Check if it's a behaviour type
                if (IsBehaviourType(typeSymbol))
                {
                    behaviourTypes.Add(typeSymbol);
                }
            }

            // Generate metadata for each behaviour type
            foreach (var typeSymbol in behaviourTypes)
            {
                var source = GenerateMetadataForType(typeSymbol);
                if (source != null)
                {
                    context.AddSource($"{typeSymbol.Name}_Metadata.g.cs", SourceText.From(source, Encoding.UTF8));
                }
            }
        }

        private bool IsBehaviourType(INamedTypeSymbol typeSymbol)
        {
            // Check if type inherits from BaseBehaviour or implements IBehaviour
            var baseType = typeSymbol.BaseType;
            while (baseType != null)
            {
                if (baseType.Name == "BaseBehaviour")
                    return true;
                baseType = baseType.BaseType;
            }

            // Check interfaces
            foreach (var @interface in typeSymbol.AllInterfaces)
            {
                if (@interface.Name == "IBehaviour")
                    return true;
            }

            return false;
        }

        private string? GenerateMetadataForType(INamedTypeSymbol typeSymbol)
        {
            // Skip if abstract or interface
            if (typeSymbol.IsAbstract || typeSymbol.TypeKind == TypeKind.Interface)
                return null;

            var namespaceName = typeSymbol.ContainingNamespace?.ToDisplayString();
            if (string.IsNullOrEmpty(namespaceName) || namespaceName == "<global namespace>")
                return null;

            var typeName = typeSymbol.Name;
            var fullTypeName = typeSymbol.ToDisplayString();
            var isGenericType = typeSymbol.IsGenericType;

            // Generate source code
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    partial class {GetTypeDeclaration(typeSymbol)} : BehaviourTree.IBehaviourMetadata");
            sb.AppendLine("    {");
            sb.AppendLine($"        string BehaviourTree.IBehaviourMetadata.TypeName => \"{typeName}\";");
            sb.AppendLine($"        string BehaviourTree.IBehaviourMetadata.FullTypeName => \"{fullTypeName}\";");
            sb.AppendLine($"        bool BehaviourTree.IBehaviourMetadata.IsGenericType => {(isGenericType ? "true" : "false")};");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private string GetTypeDeclaration(INamedTypeSymbol typeSymbol)
        {
            if (!typeSymbol.IsGenericType)
                return typeSymbol.Name;

            var typeParams = string.Join(", ", typeSymbol.TypeParameters.Select(tp => tp.Name));
            return $"{typeSymbol.Name}<{typeParams}>";
        }
    }

    /// <summary>
    /// Syntax receiver that collects all class declarations for analysis.
    /// </summary>
    internal class BehaviourSyntaxReceiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> CandidateClasses { get; } = new List<ClassDeclarationSyntax>();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            // Collect all class declarations
            if (syntaxNode is ClassDeclarationSyntax classDeclaration)
            {
                CandidateClasses.Add(classDeclaration);
            }
        }
    }
}
